name: Minimal Test

on:
  push:

jobs:
  Test-GithubActions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v2
      - name: Say Hello
        run: echo "Hello, World!"
